# Generated by Django 4.2.3 on 2023-08-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTraductor', models.CharField(max_length=50)),
                ('apellidoPaternoTraductor', models.CharField(max_length=50)),
                ('apellidoMaternoTraductor', models.CharField(max_length=50)),
                ('delExtanjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='TestigoUno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTestigoUno', models.CharField(max_length=50)),
                ('apellidoPaternoTestigoUno', models.CharField(max_length=50)),
                ('apellidoMaternoTestigoUno', models.CharField(max_length=50)),
                ('firmaTestigoUno', models.BinaryField()),
                ('huellaTestigoUno', models.BinaryField()),
                ('delExtanjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='TestigoDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTestigoDos', models.CharField(max_length=50)),
                ('apellidoPaternoTestigoDos', models.CharField(max_length=50)),
                ('apellidoMaternoTestigoDos', models.CharField(max_length=50)),
                ('firmaTestigoDos', models.BinaryField()),
                ('huellaTestigoDos', models.BinaryField()),
                ('delExtanjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
