# Generated by Django 4.2.3 on 2023-08-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extranjero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('horaRegistro', models.DateTimeField()),
                ('numeroExtranjero', models.IntegerField()),
                ('estacionMigratoria', models.CharField(max_length=50)),
                ('nombreExtranjero', models.CharField(max_length=50)),
                ('apellidoPaternoExtranjero', models.CharField(max_length=50)),
                ('apellidoMaternoExtranjero', models.CharField(max_length=50)),
                ('firmaExtranjero', models.CharField(max_length=100)),
                ('huellaExtranjero', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField()),
                ('documentoIdentidad', models.CharField(max_length=100)),
                ('fotografiaExtranjero', models.CharField(max_length=100)),
                ('viajaSolo', models.BooleanField()),
                ('voluntadPropia', models.BooleanField()),
                ('tipoEstancia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDisposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PuestaDisposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.CharField(max_length=50)),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSigna', models.CharField(max_length=100)),
                ('cargoAutoridadSigna', models.CharField(max_length=100)),
                ('oficioPuesta', models.CharField(max_length=100)),
                ('oficioComision', models.CharField(max_length=100)),
                ('deLaEstacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.estacion')),
                ('deLadisposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.tipodisposicion')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numperoUnicoProceso', models.IntegerField()),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
                ('delResponsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.responsable')),
            ],
        ),
        migrations.AddField(
            model_name='extranjero',
            name='deLaPuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicion'),
        ),
        migrations.CreateModel(
            name='ComplementoTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionOrigen', models.CharField(max_length=100)),
                ('deLaPuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicion')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementoPorTrasladar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionDestino', models.CharField(max_length=100)),
                ('deLaPuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicion')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementonAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=100)),
                ('numeroCarpeta', models.CharField(max_length=30)),
                ('entidadFederativa', models.CharField(max_length=100)),
                ('certificadoMedico', models.CharField(max_length=100)),
                ('deLaPuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicion')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementoINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntoRevision', models.CharField(max_length=100)),
                ('deLaPuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicion')),
            ],
        ),
        migrations.CreateModel(
            name='complementoAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionOrigen', models.CharField(max_length=100)),
                ('deLaPuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicion')),
            ],
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delExtranjero', models.IntegerField()),
                ('relacion', models.CharField(max_length=30)),
                ('delAcompanante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
