# Generated by Django 4.2.3 on 2023-07-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extranjero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('horaRegistro', models.DateTimeField()),
                ('numeroExtranjero', models.IntegerField()),
                ('nombreExtranjero', models.CharField(max_length=50)),
                ('apellidoPaternoExtranjero', models.CharField(max_length=50)),
                ('apellidoMaternoExtranjero', models.CharField(max_length=50)),
                ('firmaExtranjero', models.BinaryField()),
                ('huellaExtranjero', models.BinaryField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField()),
                ('documentoIdentidad', models.BinaryField()),
                ('fotografiaExtranjero', models.BinaryField()),
                ('viajaSolo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OficioPuestaDisposicionINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.IntegerField()),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSigna', models.CharField(max_length=100)),
                ('cargoAutoridadSigna', models.CharField(max_length=100)),
                ('puntoRevision', models.CharField(max_length=100)),
                ('oficioPuesta', models.BinaryField()),
                ('oficioComision', models.BinaryField()),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='OficioPuestaDisposicionAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.IntegerField()),
                ('fechaOficio', models.DateField()),
                ('dependencia', models.CharField(max_length=100)),
                ('numeroCarpeta', models.CharField(max_length=30)),
                ('nombreAutoridadSigna', models.CharField(max_length=100)),
                ('cargoAutoridadSigna', models.CharField(max_length=100)),
                ('entidadFederativa', models.CharField(max_length=100)),
                ('oficioPuesta', models.BinaryField()),
                ('certificadoMedico', models.BinaryField()),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delExtranjero', models.IntegerField()),
                ('relacion', models.CharField(max_length=30)),
                ('delAcompanante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
