# Generated by Django 4.2.3 on 2023-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficiopuestadisposicionac',
            name='numeroOficio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oficiopuestadisposicioninm',
            name='numeroOficio',
            field=models.CharField(max_length=50),
        ),
    ]
