# Generated by Django 4.2.3 on 2023-08-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigilancia', '0002_alter_oficiopuestadisposicionac_numerooficio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioPuestaDisposicionTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.CharField(max_length=50)),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSigna', models.CharField(max_length=100)),
                ('cargoAutoridadSigna', models.CharField(max_length=100)),
                ('estacionOrigen', models.CharField(max_length=100)),
                ('oficioPuesta', models.BinaryField()),
                ('oficioComision', models.BinaryField()),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='OficioPuestaDisposicionHospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.CharField(max_length=50)),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSigna', models.CharField(max_length=100)),
                ('cargoAutoridadSigna', models.CharField(max_length=100)),
                ('estacionOrigen', models.CharField(max_length=100)),
                ('oficioPuesta', models.BinaryField()),
                ('oficioComision', models.BinaryField()),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
