# Generated by Django 4.2.3 on 2023-08-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulado', models.CharField(max_length=50)),
                ('tipoResolucion', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('fechaNotificacion', models.DateField()),
                ('horaNotificacion', models.DateTimeField()),
                ('asunto', models.TextField()),
                ('documentacion', models.CharField(max_length=100)),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
