# Generated by Django 4.2.3 on 2023-07-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadMigratoria', models.CharField(max_length=30)),
                ('fechaEntrega', models.DateField()),
                ('horaEntrega', models.DateTimeField()),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.DateField(max_length=100)),
                ('cantidad', models.FloatField()),
                ('Obsevaciones', models.CharField(max_length=100)),
                ('delInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pertenencias.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Pertenencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.DateField(max_length=100)),
                ('cantidad', models.FloatField()),
                ('Obsevaciones', models.CharField(max_length=100)),
                ('delInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pertenencias.inventario')),
            ],
        ),
    ]
