# Generated by Django 4.2.3 on 2023-08-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDieta', models.CharField(max_length=50)),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEvento', models.DateField()),
                ('horaEvento', models.DateTimeField()),
                ('comida', models.BooleanField()),
                ('desayuno', models.BooleanField()),
                ('cena', models.BooleanField()),
                ('firmaExtranjero', models.CharField(max_length=100)),
                ('huellaExtranjero', models.CharField(max_length=100)),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='BoxLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEvento', models.DateField()),
                ('firmaResponsable', models.CharField(max_length=100)),
                ('huellaResponsable', models.CharField(max_length=100)),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
