# Generated by Django 4.2.3 on 2023-08-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='llamadaTelefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionMigratoria', models.CharField(max_length=50)),
                ('fechaLlamada', models.DateField()),
                ('horaLlamada', models.DateTimeField()),
                ('deseaLlamar', models.BooleanField()),
                ('motivoNoLlamada', models.TextField()),
                ('delExtranjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
