# Generated by Django 4.2.3 on 2023-08-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CertificadoMedico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadomedico',
            name='delaConsulta',
        ),
        migrations.RemoveField(
            model_name='certificadomedicoegreso',
            name='delaConsulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='delExtranjero',
        ),
        migrations.RemoveField(
            model_name='exploracionfisica',
            name='delaConsulta',
        ),
        migrations.RemoveField(
            model_name='padecimientosactuales',
            name='delaConsulta',
        ),
        migrations.RemoveField(
            model_name='perfilmedico',
            name='delaConsulta',
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='delaConsulta',
        ),
        migrations.DeleteModel(
            name='Antecedentes',
        ),
        migrations.DeleteModel(
            name='certificadoMedico',
        ),
        migrations.DeleteModel(
            name='certificadoMedicoEgreso',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='ExploracionFisica',
        ),
        migrations.DeleteModel(
            name='PadecimientosActuales',
        ),
        migrations.DeleteModel(
            name='PerfilMedico',
        ),
        migrations.DeleteModel(
            name='recetaMedica',
        ),
    ]
